services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html'
    networks:
      - app-network
    ports:
      - 9000:9000
    depends_on:
      - mysql
  mysql:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: image_compare
      MYSQL_USER: newuser
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:80:80"
    networks:
      - app-network
    volumes:
      - ./docker/nginx/default:/etc/nginx/sites-enabled/
    depends_on:
      - app
volumes:
  db-data:
networks:
  app-network:
    driver: bridge